### PR TITLE
PHP8 Compatibility

### PR DESCRIPTION
**Pull request by phpwutz**
Hi there!
Thanks for maintaining the package so far. I created this PR to get it compatible with PHP8.
PHPUnit tests ran fine with this setup, I hope its of use.
best regards

### CODE REVIEW

**Comment by pixlmint** [comment]
Would fix #56

**Comment by pixlmint** [comment]
@nacmartin How's it looking? Have you had time to look into this yet?

**Comment by phpwutz** [comment]
I've just contacted the official maintainer. after all it's already been almost 4 month. will post updates here

**Comment by nacmartin** [comment]
@phpwutz I answered your email, did you receive it?

**Comment by jandlouhy** [comment]
Hi! Any updates?

**Comment by florent-izypay** [comment]
Hi,

This would be great to have a php 8.0 migration path with this lib. It is the last piece of code preventing me from dropping php 7.
May we know if there is a plan to merge this PR ?

**Comment by jackthomasatl** [comment]
Yea. This is holding me up on being able to use this project. Can this PLEASE get merged now? Who is the maintainer?

**Comment by jackthomasatl** [comment]
@nacmartin  How's it going?

**Comment by reypm** [comment]
@nacmartin yea I am using this too and is holding me up with my PHP8 migration, any updates on this merge?

**Comment by pnovales** [comment]
Any plan soon to get this PR merge in?

**Comment by umpirsky** [comment]
@phpwutz I guess no updates? :)

**Comment by llupa** [comment]
Will this ever be merged? Is the bundle dead?

**Comment by umpirsky** [comment]
It is, RIP.

**Comment by phpwutz** [comment]
oh hey everyone.
so the current state that i'm aware of is that neither me nor the original maintainer have the resources to maintain this project. as far as i understood the original maintainer is happy to hand over the project to anyone who wants to maintain it

**Comment by umpirsky** [comment]
Can you just merge this PR? I can do it if you give me access. Thanks.

**Comment by nacmartin** [comment]
Merged, sorry and thanks for the work

**Comment by umpirsky** [comment]
Thanks, but we need [this](https://github.com/Limenius/LiformBundle/pull/32) to be able to update.

**Comment by nacmartin** [comment]
> Thanks, but we need [this](https://github.com/Limenius/LiformBundle/pull/32) to be able to update.

Done

**Comment by umpirsky** [comment]
Thanks!

My bad, looks like that was not enough:

```
  Problem 1
    - Root composer.json requires limenius/liform-bundle ^0.18 -> satisfiable by limenius/liform-bundle[v0.18.0].
    - limenius/liform-bundle v0.18.0 requires limenius/liform ^0.17 -> found limenius/liform[v0.17.0] but it conflicts with your root composer.json require (^0.18).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

Looks like we need ` "limenius/liform": "^0.17|^0.18"` https://github.com/Limenius/LiformBundle/pull/33

**Comment by nacmartin** [comment]
I see, I think we can do with the bundle in v0.18 requiring liform (the library) v0.18. Makes things simpler.

**Comment by nacmartin** [comment]
Done. (LiformBundle v0.18.1) Try it please!

**Comment by umpirsky** [comment]
Works great, thanks!

**Pull request merged**
