### PR TITLE
8.2 support

### PR DESCRIPTION
**Pull request by tacman**
This mostly reorders the parameters, since 8.2 doesn't allow optional parameters before required ones.

### CODE REVIEW

**Comment by konradkozaczenko** [comment]
Hello @tacman, do you plan to merge this PR in the near future? Can you please consider supporting version 8.4? Maybe after merge it is a good time to create new release version?

**Comment by tacman** [comment]
yes, I'll do a new release which drops outdated versions.

**Comment by tacman** [comment]
Can you please review the 2.0 release?

**Comment by konradkozaczenko** [comment]
> Can you please review the 2.0 release?

looks good. I have already implemented this version in my project and everything works and the tests pass. Thanks ;)

**Pull request merged**
