### PR TITLE
change  enum_titles to enumNames

### PR DESCRIPTION
**Pull request by videni**
According to react-jsonform-schema,  the enum_titles should be  enumNames

### CODE REVIEW

**Comment by domhaas** [comment]
> According to react-jsonform-schema, the enum_titles should be enumNames

Any chance to get this merged?

**Comment by nacmartin** [comment]
But why should we follow the conventions of react-jsonschema-form that are not part of JSON schema?

**Comment by nacmartin** [comment]
According to this discussion
https://github.com/json-schema-org/json-schema-spec/issues/57
https://github.com/json-schema-org/json-schema-spec/issues/520

JSON schema is not going that way, but in the direction of the second link. In case of changing it, it should be in that direction, if anything. As a non-standard solution, we already have enum_titles which is used by others like https://github.com/jdorn/json-editor#editor-options

So in my opinion there is no reason to change this to the (also) non-standard solution that uses another library.

**Comment by domhaas** [comment]
> According to this discussion
> [json-schema-org/json-schema-spec#57](https://github.com/json-schema-org/json-schema-spec/issues/57)
> [json-schema-org/json-schema-spec#520](https://github.com/json-schema-org/json-schema-spec/issues/520)
> 
> JSON schema is not going that way, but in the direction of the second link. In case of changing it, it should be in that direction, if anything. As a non-standard solution, we already have enum_titles which is used by others like https://github.com/jdorn/json-editor#editor-options
> 
> So in my opinion there is no reason to change this to the (also) non-standard solution that uses another library.

Thanks for the explanation. If I find time, I'm thinking to make those keys flexible (config etc.). I'm coming back If I got something to discuss.

**Comment by nacmartin** [comment]
@domhaas that would be much better, along with ways to customize it to use any of the methods. I know that the mozilla lib is popular, but it would be arbitrary to break compatibility to favour it, then address users that were relying on what we had already implemented... :S if either with config or docs or any combination we could give options for the users to choose the solution they prefer (or matches their client lib) that would be better.

**Comment by domhaas** [comment]
> @domhaas that would be much better, along with ways to customize it to use any of the methods. I know that the mozilla lib is popular, but it would be arbitrary to break compatibility to favour it, then address users that were relying on what we had already implemented... :S if either with config or docs or any combination we could give options for the users to choose the solution they prefer (or matches their client lib) that would be better.

@nacmartin full ack.
I've spent several days to evaluate json-schema libs for php and js. There are some really nice solutions out there, but they all got those troubles with different json-schema-implementations. Of course the main issue is that there is currently not a final version of a schema.
So to let users adjust those keys would be a perfect solution till there's something final.

I think there should be a config-option and also some kind of preference-settings, like to support the mozilla-lib (which got a really good attention).
Maybe there is somebody out there to support this, I'm trying this also and hopefully find some time.

**Pull request closed without merging**
